In [2]:
import numpy as np
import pandas as pd
from pandas import DataFrame
import os
from cleantext import clean

Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results.

In [3]:
arr = os.listdir('.')
print(arr)

['.DS_Store', 'DataNONEL_clean.csv', 'Untitled.ipynb', 'Clean_Tweets_EM.ipynb', 'README.md', 'Tweets_Not_ElonMusk.csv', '.gitignore', 'DataElon_clean.csv', 'Vectorisation.ipynb', '.ipynb_checkpoints', 'Clean_Tweets_NONEM.ipynb', '.git', 'TweetsElonMusk.csv']

In [4]:
DataElon = pd.read_csv('DataElon_clean.csv')
DataNONElon = pd.read_csv('DataNONEL_clean.csv')

In [5]:
def cleaner(Database_init):
    Database = Database_init.copy()   
    for i in Database.index:
        Database.loc[i, 'tweet'] = str(Database.loc[i, 'tweet']).lower()
        if '@' in str(Database.loc[i,"tweet"]):
            Tweet = Database.loc[i, 'tweet'].split(' ')
            for index, mot in enumerate(Tweet):
                if '@' in mot:
                    del Tweet[index]
            Database.loc[i, 'tweet'] = ' '.join(Tweet)
        
        Database.loc[i, 'tweet'] = clean(Database.loc[i, 'tweet'], no_emoji=True, no_punct=True, no_urls = True, replace_with_url='', no_digits=True, replace_with_digit='', no_currency_symbols=True, replace_with_currency_symbol='')
        
        
    return Database

In [6]:
def creation_mot(Liste):
    liste = [' '.join(Liste)]
    Liste_mots_doublon = liste[0].split(' ')
    for index, mot in enumerate(Liste_mots_doublon):
        if '@' in mot:
            Liste_mots_doublon[index] = ''
    Liste_mots = list(set(Liste_mots_doublon))
    return Liste_mots

In [7]:
def creation_matrice(Liste_mots, Liste):
    row =[]
    
    dictionnary = dict()
    for mot in Liste_mots:
        dictionnary[mot] = 0
    
    for tweet in Liste:
        dictionnary2 = dictionnary.copy()
        tweet_actual = tweet.split(" ")
        tweet_actual_clean = []
        for mot_tweet in tweet_actual:
            if mot_tweet != '':
                tweet_actual_clean.append(mot_tweet)
        for index, mot in enumerate(tweet_actual_clean):
            if mot in Liste_mots:
                dictionnary2[mot] = index + 1 
        row.append(dictionnary2)
    return DataFrame(row)

In [8]:
def optimize_matrice(Dataframe, n_min):
    for col in Dataframe.columns:
        if len(Dataframe[Dataframe[col] != 0]) < n_min:
            Dataframe.drop(columns = col, inplace=True)

In [9]:
DataElon = cleaner(DataElon)
Liste_tweets_EM = DataElon["tweet"].values

DataNONElon = cleaner(DataNONElon)
DataNONElon.dropna(inplace=True)
Liste_tweets_NONEM = DataNONElon["tweet"].values

In [10]:
Liste_tweets = np.concatenate((Liste_tweets_EM[:60], Liste_tweets_NONEM[:60]))

In [11]:
len(Liste_tweets)

120

In [12]:
Liste_mots = creation_mot(Liste_tweets)
len(Liste_mots)

601

In [13]:
DataBase_EM = creation_matrice(Liste_mots, Liste_tweets_EM[:60])
DataBase_EM.drop(columns = '', axis=1, inplace=True)

In [14]:
DataBase_NEM = creation_matrice(Liste_mots, Liste_tweets_NONEM[:60])
DataBase_NEM.drop(columns = '', axis=1, inplace=True)

In [15]:
DataBase = pd.concat([DataBase_EM, DataBase_NEM], ignore_index = True)

In [16]:
DataBase

,oct,behind,paralysis,cyberpunk,better,beta,matters,health,turns,use,...,ftw,scary,carol,recreate,it,earth,off,catches,hello,let
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
116,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117,0,0,0,0,0,0,0,0,0,0,...,0,19,0,0,0,0,0,0,0,0
118,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
119,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
optimize_matrice(DataBase, 3)

In [20]:
DataBase

,better,this,be,a,my,just,you,work,spacex,for,...,great,that,yes,so,like,in,radar,when,it,earth
0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,0,0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
116,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117,0,0,0,0,13,11,0,0,0,15,...,0,0,0,7,0,0,0,0,0,0
118,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
119,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,7,0,0,0,0